server:
  port: 9090

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        # SENİN YAPINA EKLEDİĞİMİZ TEK SATIR BURASI (Doğru girinti ile):
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/v1/auth/**

            - id: stock-service
              uri: http://localhost:8082
              predicates:
                - Path=/v1/product/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE